apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microhub-moderation
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: microhub-moderation
  namespaceSelector:
    matchNames:
      - ingress
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
