apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: microhub-postgres
  namespace: ingress
spec:
  serviceName: microhub-postgres
  replicas: 1
  selector:
    matchLabels:
      app: microhub-postgres
  template:
    metadata:
      labels:
        app: microhub-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: microservices
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
